### ISSUE TITLE
NUCLEO-F411RE does not have a CAN peripheral  

### ISSUE THREAD

**Issue by wrh2** [oresat/devsat#1]
We need to replace it with something that does. Perhaps with this: [NUCLEO-F412ZG](https://www.digikey.com/short/3nd881)

**Comment by wrh2** [comment]
These have been ordered to replace: https://www.digikey.com/short/3n0vzz

We should work on gathering up the kits. I'll drop mine off tonight at the meeting.

**Comment by wrh2** [comment]
Can someone confirm that all the devsat kits have had their 411 replaced with a 446?

**Comment by andrewgreenberg** [comment]
Yep! Confirmed and closing issue; only Paul's may still have a 411 board but everything should be fixed tomorrow (Tuesday) eve is so.
